syntax = "proto3";

package storage;

option go_package = "./storagepb";

service StorageService {

  rpc StoreChunk(StoreChunkRequest)
      returns (StoreChunkResponse);

  rpc GetChunk(GetChunkRequest)
      returns (GetChunkResponse);

  rpc DeleteChunk(DeleteChunkRequest)
      returns (DeleteChunkResponse);
}

message StoreChunkRequest {
  string chunk_id = 1;
  bytes data = 2;
}

message StoreChunkResponse {
  string path = 1;
}

message GetChunkRequest {
  string chunk_id = 1;
}

message GetChunkResponse {
  bytes data = 1;
}

message DeleteChunkRequest {
  string chunk_id = 1;
}

message DeleteChunkResponse {
  bool success = 1;
}
